version: '3'

services:
  dbos:
    image: mysql:5.7
    volumes: 
      - mysql-storage_new:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_USER: lalit
      MYSQL_PASSWORD: redhat
      MYSQL_DATABASE: mydb

  wordpressos:
    image: wordpress:5.1.1-php7.3-apache
    restart: always
    depend_on:
      - dbos
    ports:
      - 8081:80
    environment:
      WORDPRESS_DB_HOST: dbos
      WORDPRESS_DB_USER: lalit
      WORDPRESS_DB_PASSWORD: redhat
      WORDPRESS_DB_NAME: mydb
    volumes:
      - wordpress_storage_new:/var/www/html


volumes:
  wordpress_storage_new:
  mysql-storage_new:
    